[TASK] Add test coverage

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,21 +6,23 @@ php:
 - 7
 
 env:
-- TYPO3_VERSION=^6.2.0
-- TYPO3_VERSION=^7.6.0
+- TYPO3_VERSION=^6.2.0 COVERAGE=0
+- TYPO3_VERSION=^7.6.0 COVERAGE=0
 
 matrix:
   fast_finish: true
   exclude:
     - php: 7
-      env: TYPO3_VERSION=^6.2.0
+      env: TYPO3_VERSION=^6.2.0 COVERAGE=0
+    - php: 5.6
+      env: TYPO3_VERSION=^7.6.0 COVERAGE=1
   include:
     - php: 7
-      env: TYPO3_VERSION=^8.1.0
+      env: TYPO3_VERSION=^8.1.0 COVERAGE=0
     - php: 7
-      env: TYPO3_VERSION=dev-master
+      env: TYPO3_VERSION=dev-master COVERAGE=0
   allow_failures:
-    - env: TYPO3_VERSION=dev-master
+    - env: TYPO3_VERSION=dev-master COVERAGE=0
 
 sudo: false
 cache:
@@ -28,7 +30,10 @@ cache:
     - $HOME/.composer/cache
 
 before_install:
-  - phpenv config-rm xdebug.ini
+- |
+  if [[ "$COVERAGE" == "0" ]]; then
+    phpenv config-rm xdebug.ini
+  fi;
   - composer self-update
   - composer --version
   - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
@@ -39,23 +44,33 @@ before_script:
 
 script:
 - |
-  echo; echo "Running unit tests"; .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
+  echo; echo "Running unit tests";
+  if [[ "$COVERAGE" == "1" ]]; then
+    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml --coverage-clover=.Build/unittest-coverage.clover Tests/Unit/
+  else
+    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
+  fi;
 - |
   echo; echo "Executing PHP mess detector"; .Build/bin/phpmd Classes/ text cleancode,codesize,controversial,design,naming || true
 - |
   echo; echo "Executing PHP code sniffer"; .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/ || true
 
 after_script:
-  - >
-    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
-      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
-      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
-      if [ $? -eq 0 ]; then
-        # Cleanup before we upload
-        git reset --hard HEAD && git clean -fx
-        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
-        echo "Uploading release ${TRAVIS_TAG} to TER"
-        .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
-      fi;
+- |
+  if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
+    echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
+    curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
+    if [ $? -eq 0 ]; then
+      # Cleanup before we upload
+      git reset --hard HEAD && git clean -fx
+      TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
+      echo "Uploading release ${TRAVIS_TAG} to TER"
+      .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
     fi;
+  fi;
+- |
+  if [[ "$COVERAGE" == "1" ]]; then
+    echo; echo "Uploading code coverage results";
+    .Build/bin/ocular code-coverage:upload --format=php-clover .Build/unittest-coverage.clover
+  fi
 
